package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Event implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("EventCategory")
	private java.lang.String eventCategory;
	@org.kie.api.definition.type.Label("EventValue")
	private java.lang.String eventValue;
	@org.kie.api.definition.type.Label("EventSource")
	private java.lang.String eventSource;
	@org.kie.api.definition.type.Label("eventId")
	private java.lang.String eventId;

	public Event() {
	}

	public java.lang.String getEventCategory() {
		return this.eventCategory;
	}

	public void setEventCategory(java.lang.String eventCategory) {
		this.eventCategory = eventCategory;
	}

	public java.lang.String getEventValue() {
		return this.eventValue;
	}

	public void setEventValue(java.lang.String eventValue) {
		this.eventValue = eventValue;
	}

	public java.lang.String getEventSource() {
		return this.eventSource;
	}

	public void setEventSource(java.lang.String eventSource) {
		this.eventSource = eventSource;
	}

	public java.lang.String getEventId() {
		return this.eventId;
	}

	public void setEventId(java.lang.String eventId) {
		this.eventId = eventId;
	}

	public Event(java.lang.String eventCategory, java.lang.String eventValue,
			java.lang.String eventSource, java.lang.String eventId) {
		this.eventCategory = eventCategory;
		this.eventValue = eventValue;
		this.eventSource = eventSource;
		this.eventId = eventId;
	}

}