package com.another.personalization_rules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RulesFired implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String ruleFiredString;

	public RulesFired() {
	}

	public java.lang.String getRuleFiredString() {
		return this.ruleFiredString;
	}

	public void setRuleFiredString(java.lang.String ruleFiredString) {
		this.ruleFiredString = ruleFiredString;
	}

	public RulesFired(java.lang.String ruleFiredString) {
		this.ruleFiredString = ruleFiredString;
	}

}