package com.another.personalization_rules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RulesFired implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public RulesFired() {
    }




}